#!/bin/bash
set -e

#if is windows then use pip to install uv, else use pip3
if [[ "$OSTYPE" == "msys" ]]; then
  pip install uv
else
  pip3 install uv
fi

uv venv --python 3.11 --seed
uv run pip install -e .

# if requirements.testing.txt exists then install it
if [[ -f requirements.testing.txt ]]; then
  uv run pip install -r requirements.testing.txt
fi

# if activate exists, delete it
if [[ -f activate ]]; then
  rm activate
fi


# if windows then symlink .venv/Scripts/activate to .venv/bin/activate
if [[ "$OSTYPE" == "msys" ]]; then
  ln -s .venv/Scripts/activate ./activate
  if [[ -d .git ]]; then
    git add ./activate --chmod=+x
  fi
else
  ln -s .venv/bin/activate ./activate
fi