#!/bin/bash
set -e
source ./activate
echo Running isort
isort --profile black vidcrawler
echo Running black
black vidcrawler
echo Running ruff
ruff check vidcrawler
echo Running flake8 vidcrawler
flake8 vidcrawler
echo Running mypy vidcrawler
mypy vidcrawler
echo Linting complete!