#!/bin/bash
set -e
# cd to self bash script directory
cd $( dirname ${BASH_SOURCE[0]})
echo Running isort
isort --profile black vidcrawler
echo Running black
black vidcrawler
echo Running flake8 vidcrawler
flake8 vidcrawler
echo Running pylint vidcrawler
pylint vidcrawler
echo Running mypy vidcrawler
mypy vidcrawler
echo Linting complete!